"""Transcript-consolidation null compatibility exports."""

from experiments.consolidation.null import (
    CODE_DIGITS,
    ENTITY_POOL,
    FILLER_SENTENCES,
    GEN_TOKENS,
    PASS_MATCH_RATE,
    UNDERPOWERED_DELTA_NATS,
    Fact,
    Turn,
    build_facts,
    build_turns,
    contains_code,
    cue_rungs,
    digits,
    exact_match,
    extract_answer,
    fact_turns,
    first_success,
    fmt_duration,
    generate,
    kl_loss,
    main,
    normalize,
    pass_at_k,
    render_turns,
    replay_step,
    report_transcript,
    role_adjacency_violations,
    run_chunks,
    target_logprob,
    ts,
    verdict,
)

__all__ = [
    "CODE_DIGITS",
    "ENTITY_POOL",
    "FILLER_SENTENCES",
    "Fact",
    "Turn",
    "build_facts",
    "build_turns",
    "contains_code",
    "cue_rungs",
    "digits",
    "exact_match",
    "extract_answer",
    "fact_turns",
    "first_success",
    "normalize",
    "pass_at_k",
    "render_turns",
    "role_adjacency_violations",
    "generate",
    "kl_loss",
    "replay_step",
    "run_chunks",
    "target_logprob",
    "fmt_duration",
    "ts",
    "PASS_MATCH_RATE",
    "UNDERPOWERED_DELTA_NATS",
    "GEN_TOKENS",
    "verdict",
    "report_transcript",
    "main",
]


if __name__ == "__main__":
    main()
